let boomhauer_speak = [
  'Yeah man',
  'I tell ya what',
  'man',
  'Yeah man, I tell ya what, man',
  'Dang ol love',
  'Talking about',
  'bygones be bygones, man',
  'and dont do a dang',
  'Yep.',
  'just dang ol fell on my dang behind',
  'woo hoo dog!',
  'Ill tell you what',
  'No dad gum way man',
  'dang ol cant speak language of dang love'
  'talkin bout tasting his own burp',
  'dang ol leave ol Chet alone',
  ' moneys like dang ol wind ',
  'Pee ol dang ol u',
  'Fried filet of fried chicken',
  'french fried side of fries',
  'oh man, done deg ol why, deg',
  'danged ol danged if you ol danged if ya dont dang',
]
